### ISSUE TITLE
Refactor consumption of policy Helm charts

### ISSUE THREAD

**Issue by viccuad** [rancher/kubewarden-ui#1215]
Kubewarden policies are shipped to be consumed by Kubewarden UI via Helm charts, that contain the policy metadata and a `questions.yaml`. They live in [github.com/kubewarden/policy-catalog](https://github.com/kubewarden/policy-catalog) Helm chart repository, under charts/. 

Up until now, the metadata to obtain the OCI artifact for the policy was included in the Chart.yaml as annotations:
```yaml
# Chart.yaml
annotations:
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/ingress
  kubewarden/tag: v1.0.0
```

This is ok, but users cannot overwrite it easily for airgap installations.

With, https://github.com/kubewarden/policy-catalog/issues/454, we have changed how we build the policy Helm charts so they ship a `values.yaml` with the following content:

```yaml
global:
  cattle:
    systemDefaultRegistry: ghcr.io
module: # policy module
  # The registry is defined in the global.cattle.systemDefaultRegistry value
  # policy to be used
  repository: "kubewarden/policies/user-group-psp"
  # policy tag
  tag: v1.0.0
```

For now, we are preserving the Chart.yaml annotations and marking them as deprecated. We will remove them once the UI is ready to consume values.yaml, so releasing new policy versions doesn't break the policies installation via the UI. The removal of the deprecation is tracked in https://github.com/kubewarden/policy-catalog/issues/471.

This whole change is explained in our RFC, via https://github.com/kubewarden/rfc/pull/50

### Acceptance criteria

We have released a new version of the `sysctl-psp-policy`. In its version `1.0.2`, it contains both the deprecated Chart.yaml annotations and the new `values.yaml`. The rest of the policies will get released automatically via our automated monthly jobs.

- Adapt the Kubewarden UI code done in https://github.com/rancher/kubewarden-ui/commit/ee9398d9b0defc8f18ff6111b69664b13722b299, so from now on, we consume the values for the OCI registry that get used in the policies' `spec.module` come from the values.yaml if it exists, or use the Chart.yaml annotations as a fallback.
  - If the values.yaml exists, allow users to overwrite the default registry, repository, and tag, when creating the policy via the form.

- Allow a migration path of policies that support old Chart.yaml annotations and new values.yaml as:
    - Users need to be able to update the Kubewarden UI without updating all the policies.
    - Users need to be able to keep the old Kubewarden UI (that only supports Chart.yaml) and update to the new policies.
  One option (preferable from my point of view) would be to backport the values.yaml support to old UI versions.
  Another option is declare a Kubewarden UI minor version that supports it, and then we wait until the rest have been phased out.

- [ ] Provide E2E tests of policy installations that use the new values.yaml.
