### ISSUE TITLE
Trusted Repos: only one of allow or reject can be provided and one must be provided

### ISSUE THREAD

**Issue by kravciak** [rancher/kubewarden-ui#308]
### Current Behavior

[Policy definition](https://github.com/kubewarden/trusted-repos-policy/blob/main/README.md#what-the-policy-allows-to-restrict) says:
 - you can mix and match several filters: registries, tags, and images
 - only one allow / reject can be provided at the same time for that specific filter

Default yaml contains all filters as empty object:
```yaml
  settings:
    registries: {}
    tags: {}
    images: {}
```

This is problem because policy thinks all filters are defined and expect exactly one rule for them.
- I am not able to create policy without any settings. It thinks I defined all filters without any allow/reject rules)
- When I add & remove rule it leaves empty `allow: []` or `reject: []`. This again breaks rule about exactly one allow/reject rule.

Errors in log:
```yaml
# policy without any settings:
settings are not valid: Some("only one of registries allow or reject can be provided, and one must be provided")

# policy with valid valid registries setting
settings are not valid: Some("only one of images allow or reject can be provided, and one must be provided")
```

**Comment by kravciak** [comment]
Reopening the issue. To reproduce take first example from [README](https://artifacthub.io/packages/kubewarden/trusted-repos/trusted-repos#examples):

- open settings
- use registries -> allow: registry.my-corp.com

I end up with following settings yaml:
```
  settings:
    registries:
      allow:
        - registry.my-corp.com
    tags: {}
    images: {}
```

After creating such policy I get following error from policyserver
```
ERROR policy_server::worker_pool: cannot validate policy settings error=[clusterwide-tr] settings are not valid: Some("only one of images allow or reject can be provided, and one must be provided")
ERROR policy_server: [clusterwide-tr] settings are not valid: Some("only one of images allow or reject can be provided, and one must be provided")
```
