### ISSUE TITLE
Fleet: The latest stable version for Policy Server could not be determined

### ISSUE THREAD

**Issue by kravciak** [rancher/kubewarden-ui#572]
![Screenshot from 2023-12-08 14-26-55](https://github.com/rancher/kubewarden-ui/assets/538604/8e5049be-d0b2-4021-a506-befa26cf928a)

To reproduce:
 - create k3d cluster, install rancher
 - install kubewarden extension
 - import second cluster
 - add extra cluster, use same network as first one `k3d cluster create --network <docker network list ^^^> toimport`
 - add fleet repository (use `https://github.com/kravciak/kubewarden-ui.git`, `branch: fleet`, `path: tests/e2e/fleet/`, or use fleet.yaml structure below

```yaml
# == fleet/cert-manager/fleet.yaml ==
defaultNamespace: cert-manager

helm:
  releaseName: cert-manager
  chart: cert-manager
  version: 1.13.2
  repo: https://charts.jetstack.io
  values:
    installCRDs: true

labels:
  app: cert-manager

# == fleet/kubewarden/controller/fleet.yaml ==
defaultNamespace: cattle-kubewarden-system

helm:
  # version: 2.0.5
  releaseName: kubewarden-controller
  chart: kubewarden-controller
  repo: https://charts.kubewarden.io
  values:
    auditScanner:
      policyReporter: true

labels:
  app: kubewarden-controller

dependsOn:
  - selector:
      matchLabels:
        app: cert-manager
  - selector:
      matchLabels:
        app: kubewarden-crds

# == fleet/kubewarden/crds/fleet.yaml ==
defaultNamespace: cattle-kubewarden-system

helm:
  # version: 1.4.4
  releaseName: kubewarden-crds
  chart: kubewarden-crds
  repo: https://charts.kubewarden.io

labels:
  app: kubewarden-crds

# == fleet/kubewarden/defaults/fleet.yaml ==
defaultNamespace: cattle-kubewarden-system

helm:
  # version: 1.9.2
  releaseName: kubewarden-defaults
  chart: kubewarden-defaults
  repo: https://charts.kubewarden.io
  values:
    recommendedPolicies:
      enabled: true

labels:
  app: kubewarden-defaults

dependsOn:
  - selector:
      matchLabels:
        app: kubewarden-controller

```

**Comment by jordojordo** [comment]
The issue is due to the defaults chart not having any versions listed as this is expected [here](https://github.com/rancher/kubewarden-ui/blob/1f5a10ffb32abd09f5d50cf29cf93dc6c4e54343/pkg/kubewarden/chart/kubewarden/policy-server/General.vue#L49). Is this a typical situation where someone installing kubewarden with fleet will not have any versions tied to the charts?

**Comment by kravciak** [comment]
You are probably right, I am also mixing fleet setup with manual management. I will try with versions.

**Comment by kravciak** [comment]
I added versions to fleet.yaml, but I see no change - I still get `policy-server:latest`.

Fleet yaml changed to:
```yaml
# == fleet/kubewarden/controller/fleet.yaml ==
helm:
  version: 2.0.5
  releaseName: kubewarden-controller
...

# == fleet/kubewarden/crds/fleet.yaml ==
helm:
  version: 1.4.4
  releaseName: kubewarden-crds
...

# == fleet/kubewarden/defaults/fleet.yaml ==
helm:
  version: 1.9.2
  releaseName: kubewarden-defaults
...
```
